// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.wewrite;

public final class EventProtos {
  private EventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 userId = 2;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 2;</code>
     */
    int getUserId();

    // optional int32 moveType = 5;
    /**
     * <code>optional int32 moveType = 5;</code>
     */
    boolean hasMoveType();
    /**
     * <code>optional int32 moveType = 5;</code>
     */
    int getMoveType();

    // optional string data = 6;
    /**
     * <code>optional string data = 6;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 6;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 6;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    // optional int32 cursorChange = 7;
    /**
     * <code>optional int32 cursorChange = 7;</code>
     */
    boolean hasCursorChange();
    /**
     * <code>optional int32 cursorChange = 7;</code>
     */
    int getCursorChange();

    // optional bool undo = 8;
    /**
     * <code>optional bool undo = 8;</code>
     */
    boolean hasUndo();
    /**
     * <code>optional bool undo = 8;</code>
     */
    boolean getUndo();
  }
  /**
   * Protobuf type {@code com.wewrite.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              moveType_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000008;
              cursorChange_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000010;
              undo_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wewrite.EventProtos.internal_static_com_wewrite_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wewrite.EventProtos.Event.class, com.wewrite.EventProtos.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 moveType = 5;
    public static final int MOVETYPE_FIELD_NUMBER = 5;
    private int moveType_;
    /**
     * <code>optional int32 moveType = 5;</code>
     */
    public boolean hasMoveType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 moveType = 5;</code>
     */
    public int getMoveType() {
      return moveType_;
    }

    // optional string data = 6;
    public static final int DATA_FIELD_NUMBER = 6;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 6;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string data = 6;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 cursorChange = 7;
    public static final int CURSORCHANGE_FIELD_NUMBER = 7;
    private int cursorChange_;
    /**
     * <code>optional int32 cursorChange = 7;</code>
     */
    public boolean hasCursorChange() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 cursorChange = 7;</code>
     */
    public int getCursorChange() {
      return cursorChange_;
    }

    // optional bool undo = 8;
    public static final int UNDO_FIELD_NUMBER = 8;
    private boolean undo_;
    /**
     * <code>optional bool undo = 8;</code>
     */
    public boolean hasUndo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool undo = 8;</code>
     */
    public boolean getUndo() {
      return undo_;
    }

    private void initFields() {
      userId_ = 0;
      moveType_ = 0;
      data_ = "";
      cursorChange_ = 0;
      undo_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(5, moveType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(6, getDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(7, cursorChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(8, undo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, moveType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDataBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, cursorChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, undo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wewrite.EventProtos.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wewrite.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wewrite.EventProtos.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wewrite.EventProtos.Event.class, com.wewrite.EventProtos.Event.Builder.class);
      }

      // Construct using com.wewrite.EventProtos.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        moveType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cursorChange_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        undo_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
      }

      public com.wewrite.EventProtos.Event getDefaultInstanceForType() {
        return com.wewrite.EventProtos.Event.getDefaultInstance();
      }

      public com.wewrite.EventProtos.Event build() {
        com.wewrite.EventProtos.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wewrite.EventProtos.Event buildPartial() {
        com.wewrite.EventProtos.Event result = new com.wewrite.EventProtos.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.moveType_ = moveType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cursorChange_ = cursorChange_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.undo_ = undo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wewrite.EventProtos.Event) {
          return mergeFrom((com.wewrite.EventProtos.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wewrite.EventProtos.Event other) {
        if (other == com.wewrite.EventProtos.Event.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMoveType()) {
          setMoveType(other.getMoveType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000004;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasCursorChange()) {
          setCursorChange(other.getCursorChange());
        }
        if (other.hasUndo()) {
          setUndo(other.getUndo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wewrite.EventProtos.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wewrite.EventProtos.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 userId = 2;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 moveType = 5;
      private int moveType_ ;
      /**
       * <code>optional int32 moveType = 5;</code>
       */
      public boolean hasMoveType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       */
      public int getMoveType() {
        return moveType_;
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       */
      public Builder setMoveType(int value) {
        bitField0_ |= 0x00000002;
        moveType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       */
      public Builder clearMoveType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        moveType_ = 0;
        onChanged();
        return this;
      }

      // optional string data = 6;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 6;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string data = 6;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 6;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 6;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 6;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }

      // optional int32 cursorChange = 7;
      private int cursorChange_ ;
      /**
       * <code>optional int32 cursorChange = 7;</code>
       */
      public boolean hasCursorChange() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       */
      public int getCursorChange() {
        return cursorChange_;
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       */
      public Builder setCursorChange(int value) {
        bitField0_ |= 0x00000008;
        cursorChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       */
      public Builder clearCursorChange() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorChange_ = 0;
        onChanged();
        return this;
      }

      // optional bool undo = 8;
      private boolean undo_ ;
      /**
       * <code>optional bool undo = 8;</code>
       */
      public boolean hasUndo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool undo = 8;</code>
       */
      public boolean getUndo() {
        return undo_;
      }
      /**
       * <code>optional bool undo = 8;</code>
       */
      public Builder setUndo(boolean value) {
        bitField0_ |= 0x00000010;
        undo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool undo = 8;</code>
       */
      public Builder clearUndo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        undo_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wewrite.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wewrite.Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wewrite_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wewrite_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\013com.wewrite\"[\n\005Event\022\016" +
      "\n\006userId\030\002 \001(\005\022\020\n\010moveType\030\005 \001(\005\022\014\n\004data" +
      "\030\006 \001(\t\022\024\n\014cursorChange\030\007 \001(\005\022\014\n\004undo\030\010 \001" +
      "(\010B\032\n\013com.wewriteB\013EventProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wewrite_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wewrite_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wewrite_Event_descriptor,
              new java.lang.String[] { "UserId", "MoveType", "Data", "CursorChange", "Undo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
