// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/wewrite/messages.proto

package com.wewrite;

public final class EventProtos {
  private EventProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string beforeText = 1;
    /**
     * <code>optional string beforeText = 1;</code>
     */
    boolean hasBeforeText();
    /**
     * <code>optional string beforeText = 1;</code>
     */
    java.lang.String getBeforeText();
    /**
     * <code>optional string beforeText = 1;</code>
     */
    com.google.protobuf.ByteString
        getBeforeTextBytes();

    // optional string afterText = 2;
    /**
     * <code>optional string afterText = 2;</code>
     */
    boolean hasAfterText();
    /**
     * <code>optional string afterText = 2;</code>
     */
    java.lang.String getAfterText();
    /**
     * <code>optional string afterText = 2;</code>
     */
    com.google.protobuf.ByteString
        getAfterTextBytes();

    // optional string diffText = 3;
    /**
     * <code>optional string diffText = 3;</code>
     */
    boolean hasDiffText();
    /**
     * <code>optional string diffText = 3;</code>
     */
    java.lang.String getDiffText();
    /**
     * <code>optional string diffText = 3;</code>
     */
    com.google.protobuf.ByteString
        getDiffTextBytes();

    // optional int32 start = 4;
    /**
     * <code>optional int32 start = 4;</code>
     */
    boolean hasStart();
    /**
     * <code>optional int32 start = 4;</code>
     */
    int getStart();

    // optional int32 length = 5;
    /**
     * <code>optional int32 length = 5;</code>
     */
    boolean hasLength();
    /**
     * <code>optional int32 length = 5;</code>
     */
    int getLength();

    // optional bool type = 6;
    /**
     * <code>optional bool type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>optional bool type = 6;</code>
     */
    boolean getType();

    // optional int32 cursorLocationAfter = 7;
    /**
     * <code>optional int32 cursorLocationAfter = 7;</code>
     */
    boolean hasCursorLocationAfter();
    /**
     * <code>optional int32 cursorLocationAfter = 7;</code>
     */
    int getCursorLocationAfter();

    // optional int32 cursorLocationBefore = 8;
    /**
     * <code>optional int32 cursorLocationBefore = 8;</code>
     */
    boolean hasCursorLocationBefore();
    /**
     * <code>optional int32 cursorLocationBefore = 8;</code>
     */
    int getCursorLocationBefore();
  }
  /**
   * Protobuf type {@code com.wewrite.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              beforeText_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              afterText_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              diffText_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              start_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              length_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              type_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              cursorLocationAfter_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              cursorLocationBefore_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wewrite.EventProtos.internal_static_com_wewrite_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wewrite.EventProtos.Event.class, com.wewrite.EventProtos.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string beforeText = 1;
    public static final int BEFORETEXT_FIELD_NUMBER = 1;
    private java.lang.Object beforeText_;
    /**
     * <code>optional string beforeText = 1;</code>
     */
    public boolean hasBeforeText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string beforeText = 1;</code>
     */
    public java.lang.String getBeforeText() {
      java.lang.Object ref = beforeText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          beforeText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string beforeText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBeforeTextBytes() {
      java.lang.Object ref = beforeText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        beforeText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string afterText = 2;
    public static final int AFTERTEXT_FIELD_NUMBER = 2;
    private java.lang.Object afterText_;
    /**
     * <code>optional string afterText = 2;</code>
     */
    public boolean hasAfterText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string afterText = 2;</code>
     */
    public java.lang.String getAfterText() {
      java.lang.Object ref = afterText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          afterText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string afterText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAfterTextBytes() {
      java.lang.Object ref = afterText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        afterText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string diffText = 3;
    public static final int DIFFTEXT_FIELD_NUMBER = 3;
    private java.lang.Object diffText_;
    /**
     * <code>optional string diffText = 3;</code>
     */
    public boolean hasDiffText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string diffText = 3;</code>
     */
    public java.lang.String getDiffText() {
      java.lang.Object ref = diffText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          diffText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string diffText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDiffTextBytes() {
      java.lang.Object ref = diffText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        diffText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 start = 4;
    public static final int START_FIELD_NUMBER = 4;
    private int start_;
    /**
     * <code>optional int32 start = 4;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 start = 4;</code>
     */
    public int getStart() {
      return start_;
    }

    // optional int32 length = 5;
    public static final int LENGTH_FIELD_NUMBER = 5;
    private int length_;
    /**
     * <code>optional int32 length = 5;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 length = 5;</code>
     */
    public int getLength() {
      return length_;
    }

    // optional bool type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private boolean type_;
    /**
     * <code>optional bool type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool type = 6;</code>
     */
    public boolean getType() {
      return type_;
    }

    // optional int32 cursorLocationAfter = 7;
    public static final int CURSORLOCATIONAFTER_FIELD_NUMBER = 7;
    private int cursorLocationAfter_;
    /**
     * <code>optional int32 cursorLocationAfter = 7;</code>
     */
    public boolean hasCursorLocationAfter() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 cursorLocationAfter = 7;</code>
     */
    public int getCursorLocationAfter() {
      return cursorLocationAfter_;
    }

    // optional int32 cursorLocationBefore = 8;
    public static final int CURSORLOCATIONBEFORE_FIELD_NUMBER = 8;
    private int cursorLocationBefore_;
    /**
     * <code>optional int32 cursorLocationBefore = 8;</code>
     */
    public boolean hasCursorLocationBefore() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 cursorLocationBefore = 8;</code>
     */
    public int getCursorLocationBefore() {
      return cursorLocationBefore_;
    }

    private void initFields() {
      beforeText_ = "";
      afterText_ = "";
      diffText_ = "";
      start_ = 0;
      length_ = 0;
      type_ = false;
      cursorLocationAfter_ = 0;
      cursorLocationBefore_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBeforeTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAfterTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDiffTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, length_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, cursorLocationAfter_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, cursorLocationBefore_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBeforeTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAfterTextBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDiffTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, length_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, cursorLocationAfter_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cursorLocationBefore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wewrite.EventProtos.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wewrite.EventProtos.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wewrite.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.wewrite.EventProtos.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wewrite.EventProtos.Event.class, com.wewrite.EventProtos.Event.Builder.class);
      }

      // Construct using com.wewrite.EventProtos.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        beforeText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        afterText_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        diffText_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        cursorLocationAfter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        cursorLocationBefore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wewrite.EventProtos.internal_static_com_wewrite_Event_descriptor;
      }

      public com.wewrite.EventProtos.Event getDefaultInstanceForType() {
        return com.wewrite.EventProtos.Event.getDefaultInstance();
      }

      public com.wewrite.EventProtos.Event build() {
        com.wewrite.EventProtos.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wewrite.EventProtos.Event buildPartial() {
        com.wewrite.EventProtos.Event result = new com.wewrite.EventProtos.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.beforeText_ = beforeText_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.afterText_ = afterText_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.diffText_ = diffText_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cursorLocationAfter_ = cursorLocationAfter_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.cursorLocationBefore_ = cursorLocationBefore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wewrite.EventProtos.Event) {
          return mergeFrom((com.wewrite.EventProtos.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wewrite.EventProtos.Event other) {
        if (other == com.wewrite.EventProtos.Event.getDefaultInstance()) return this;
        if (other.hasBeforeText()) {
          bitField0_ |= 0x00000001;
          beforeText_ = other.beforeText_;
          onChanged();
        }
        if (other.hasAfterText()) {
          bitField0_ |= 0x00000002;
          afterText_ = other.afterText_;
          onChanged();
        }
        if (other.hasDiffText()) {
          bitField0_ |= 0x00000004;
          diffText_ = other.diffText_;
          onChanged();
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCursorLocationAfter()) {
          setCursorLocationAfter(other.getCursorLocationAfter());
        }
        if (other.hasCursorLocationBefore()) {
          setCursorLocationBefore(other.getCursorLocationBefore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wewrite.EventProtos.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wewrite.EventProtos.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string beforeText = 1;
      private java.lang.Object beforeText_ = "";
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public boolean hasBeforeText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public java.lang.String getBeforeText() {
        java.lang.Object ref = beforeText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          beforeText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBeforeTextBytes() {
        java.lang.Object ref = beforeText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          beforeText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public Builder setBeforeText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        beforeText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public Builder clearBeforeText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        beforeText_ = getDefaultInstance().getBeforeText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string beforeText = 1;</code>
       */
      public Builder setBeforeTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        beforeText_ = value;
        onChanged();
        return this;
      }

      // optional string afterText = 2;
      private java.lang.Object afterText_ = "";
      /**
       * <code>optional string afterText = 2;</code>
       */
      public boolean hasAfterText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string afterText = 2;</code>
       */
      public java.lang.String getAfterText() {
        java.lang.Object ref = afterText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          afterText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string afterText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAfterTextBytes() {
        java.lang.Object ref = afterText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          afterText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string afterText = 2;</code>
       */
      public Builder setAfterText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        afterText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string afterText = 2;</code>
       */
      public Builder clearAfterText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        afterText_ = getDefaultInstance().getAfterText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string afterText = 2;</code>
       */
      public Builder setAfterTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        afterText_ = value;
        onChanged();
        return this;
      }

      // optional string diffText = 3;
      private java.lang.Object diffText_ = "";
      /**
       * <code>optional string diffText = 3;</code>
       */
      public boolean hasDiffText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string diffText = 3;</code>
       */
      public java.lang.String getDiffText() {
        java.lang.Object ref = diffText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          diffText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string diffText = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDiffTextBytes() {
        java.lang.Object ref = diffText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          diffText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string diffText = 3;</code>
       */
      public Builder setDiffText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        diffText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string diffText = 3;</code>
       */
      public Builder clearDiffText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        diffText_ = getDefaultInstance().getDiffText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string diffText = 3;</code>
       */
      public Builder setDiffTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        diffText_ = value;
        onChanged();
        return this;
      }

      // optional int32 start = 4;
      private int start_ ;
      /**
       * <code>optional int32 start = 4;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public int getStart() {
        return start_;
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public Builder setStart(int value) {
        bitField0_ |= 0x00000008;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 start = 4;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        start_ = 0;
        onChanged();
        return this;
      }

      // optional int32 length = 5;
      private int length_ ;
      /**
       * <code>optional int32 length = 5;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 length = 5;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>optional int32 length = 5;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000010;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 length = 5;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0;
        onChanged();
        return this;
      }

      // optional bool type = 6;
      private boolean type_ ;
      /**
       * <code>optional bool type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool type = 6;</code>
       */
      public boolean getType() {
        return type_;
      }
      /**
       * <code>optional bool type = 6;</code>
       */
      public Builder setType(boolean value) {
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = false;
        onChanged();
        return this;
      }

      // optional int32 cursorLocationAfter = 7;
      private int cursorLocationAfter_ ;
      /**
       * <code>optional int32 cursorLocationAfter = 7;</code>
       */
      public boolean hasCursorLocationAfter() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 cursorLocationAfter = 7;</code>
       */
      public int getCursorLocationAfter() {
        return cursorLocationAfter_;
      }
      /**
       * <code>optional int32 cursorLocationAfter = 7;</code>
       */
      public Builder setCursorLocationAfter(int value) {
        bitField0_ |= 0x00000040;
        cursorLocationAfter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLocationAfter = 7;</code>
       */
      public Builder clearCursorLocationAfter() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cursorLocationAfter_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cursorLocationBefore = 8;
      private int cursorLocationBefore_ ;
      /**
       * <code>optional int32 cursorLocationBefore = 8;</code>
       */
      public boolean hasCursorLocationBefore() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 cursorLocationBefore = 8;</code>
       */
      public int getCursorLocationBefore() {
        return cursorLocationBefore_;
      }
      /**
       * <code>optional int32 cursorLocationBefore = 8;</code>
       */
      public Builder setCursorLocationBefore(int value) {
        bitField0_ |= 0x00000080;
        cursorLocationBefore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLocationBefore = 8;</code>
       */
      public Builder clearCursorLocationBefore() {
        bitField0_ = (bitField0_ & ~0x00000080);
        cursorLocationBefore_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wewrite.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wewrite.Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wewrite_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wewrite_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/com/wewrite/messages.proto\022\013com.we" +
      "write\"\250\001\n\005Event\022\022\n\nbeforeText\030\001 \001(\t\022\021\n\ta" +
      "fterText\030\002 \001(\t\022\020\n\010diffText\030\003 \001(\t\022\r\n\005star" +
      "t\030\004 \001(\005\022\016\n\006length\030\005 \001(\005\022\014\n\004type\030\006 \001(\010\022\033\n" +
      "\023cursorLocationAfter\030\007 \001(\005\022\034\n\024cursorLoca" +
      "tionBefore\030\010 \001(\005B\032\n\013com.wewriteB\013EventPr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_wewrite_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_wewrite_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_wewrite_Event_descriptor,
              new java.lang.String[] { "BeforeText", "AfterText", "DiffText", "Start", "Length", "Type", "CursorLocationAfter", "CursorLocationBefore", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
